version: 0.1
environment_variables:
  plaintext:
    S3_BUCKET_NAME: "www.registration-unichain.com"
phases:
  install:
    commands:
      - cd dapp
      - npm install
      - npm run-script build
artifacts:
  files:
    - '**/*'
  base-directory: 'docs*'
  discard-paths: yes
